ActivityTracker/Models/Activity.cs
using System.Collections.Generic;

namespace ActivityTracker.Models
{
    public class Activity
    {
        public int ID { get; set; }
        public string ApplicationUserID { get; set; }

        public string Name { get; set; }
        public bool Complete { get; set; }
        public int? FunFactor { get; set; }
        public int? Difficulty { get; set; }
        public string Notes { get; set; }

        public ApplicationUser Student { get; set; }

        public ICollection<LogEntry> Log { get; set; }

        public static bool AuthorizeActivityUser(Activity activity, ApplicationUser currentUser)
        {
            if (currentUser.UserType == "S")
            {
                if (activity.ApplicationUserID != currentUser.Id)
                {
                    return false;
                }
                else
                    return true;
            }
            else
            {
                if (currentUser.Id != activity.Student.TeacherID)
                {
                    return false;
                }
                else
                    return true;
            }
        }
    }
}

ActivityTracker/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ActivityTracker.Data;
using ActivityTracker.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ActivityTracker.Controllers
{
    public class ActivitiesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ActivitiesController(ApplicationDbContext context,
                                    UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public IQueryable<Activity> GetAllActivities()
        {
            return _context.Activities.AsQueryable();
        }

        public IQueryable<ApplicationUser> GetAllStudents()
        {
            return _context.ApplicationUsers.AsQueryable();
        }

        // GET: Activities
        public async Task<IActionResult> Index(string id)
        {
            var currentUser = await GetCurrentUserAsync();
            ViewBag.CurrentUserType = currentUser.UserType;

            string studentId;
            if (currentUser.UserType == "S")
            {
                studentId = currentUser.Id;
                ViewBag.studentId = studentId;
            }
            else
            {
                try
                {
                    var student = GetAllStudents().Where(u => u.Id == id).ToList()[0];
                    studentId = id;
                    ViewBag.studentId = id;
                    ViewBag.StudentName = String.Format("{0} {1} {2}", student.FirstName, student.Prefix, student.LastName);
                    ViewBag.Groups = new List<Group>();
                    var allGroups = await _context.Groups
                        .Where(group => group.OwnerID == currentUser.Id)
                        .Include(group => group.UserGroups)
                            .ThenInclude(userGroup => userGroup.Student)
                        .ToListAsync();
                    foreach (var group in allGroups)
                    {
                        foreach (var userGroup in group.UserGroups)
                        {
                            if (userGroup.Student == student)
                            {
                                ViewBag.Groups.Add(group);
                            }
                        }
                    }
                }
                catch (ArgumentOutOfRangeException)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            var activities = GetAllActivities().Where(a => a.ApplicationUserID == studentId).OrderBy(a => a.Name).
                OrderBy(a => a.Complete).ToList();

            foreach (var activity in activities)
            {
                if (activity.Notes != null)
                {
                    activity.Notes = activity.Notes.Split(new[] { '.', '\r', '\n' }).FirstOrDefault();
                }
            }

            ViewBag.Activities = activities;

            return View();
        }

        // GET: Activities/Create
        public async Task<IActionResult> Create()
        {
            var currentUser = await GetCurrentUserAsync();

            if (currentUser.UserType == "S")
            {
                ViewBag.CurrentUserType = "S";
            }
            ViewBag.StudentId = HttpContext.Request.Query["studentid"];
            return View();
        }

        // POST: Activities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ApplicationUserID,Name,Complete,FunFactor,Difficulty,Notes")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await GetCurrentUserAsync();
                string studentId;

                if (currentUser.UserType == "S")
                {
                    studentId = currentUser.Id;
                    ViewBag.CurrentUserType = "S";
                }
                else if (currentUser.UserType == "T")
                {
                    studentId = HttpContext.Request.Query["id"];
                    ViewBag.CurrentUserType = "T";
                }
                else
                {
                    throw new ApplicationException("Not a valid UserType");
                }

                _context.Add(activity);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = activity.ApplicationUserID });
            }
            return View(activity);
        }

        public IQueryable<LogEntry> GetAllLogEntries()
        {
            return _context.LogEntries.AsQueryable();
        }

        // GET: Activities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var currentUser = await GetCurrentUserAsync();
            ViewBag.CurrentUser = currentUser;

            var logEntries = GetAllLogEntries().Where(le => le.ActivityID == id).
                OrderByDescending(le => le.Date).ToList();

            ViewBag.LogEntries = logEntries;

            try
            {
                ViewBag.StartDate = logEntries.Min(x => x.Date).ToString("dd-MM-yyyy");
                ViewBag.TimeSpent = logEntries.Sum(x => x.TimeSpent);
                ViewBag.LastActivity = logEntries.Max(x => x.Date).ToString("dd-MM-yyyy");
            }
            catch (InvalidOperationException)
            {
                // do nothing
            }

            var activity = await _context.Activities
                .Include(a => a.Student)
                .SingleOrDefaultAsync(m => m.ID == id);

            if (activity == null)
            {
                return NotFound();
            }

            if (Activity.AuthorizeActivityUser(activity, currentUser))
                return View(activity);
            else
                return RedirectToAction("AccessDenied", "Account");
        }

        // POST: Activities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ApplicationUserID,Name,Complete,FunFactor,Difficulty,Notes")] Activity activity)
        {
            if (id != activity.ID)
            {
                return NotFound();
            }
            var currentUser = await GetCurrentUserAsync();
            string teacherId = "";

            if (currentUser.UserType == "T")
            {
                teacherId = _context.ApplicationUsers
                    .Where(au => au.Id == activity.ApplicationUserID)
                    .FirstOrDefault()
                    .TeacherID;
            }

            if (activity.ApplicationUserID == currentUser.Id ||
                teacherId == currentUser.Id)
            {
                if (ModelState.IsValid)
                {
                    return await NewMethod(activity, currentUser);
                }
                return View(activity);
            }
            else
                return RedirectToAction("AccessDenied", "Account");
        }

        private async Task<IActionResult> NewMethod(Activity activity, ApplicationUser currentUser)
        {
            try
            {
                _context.Update(activity);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ActivityExists(activity.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            if (currentUser.UserType == "S")
                return RedirectToAction(nameof(Index));
            else
                return RedirectToAction("Index", "Activities", new { id = activity.ApplicationUserID });
        }

        // GET: Activities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activity = await _context.Activities
                .SingleOrDefaultAsync(m => m.ID == id);
            if (activity == null)
            {
                return NotFound();
            }

            var currentUser = await GetCurrentUserAsync();

            if (activity.ApplicationUserID == currentUser.Id)
            {
                return View(activity);
            }
            else
                return RedirectToAction("AccessDenied", "Account");
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activity = await _context.Activities.SingleOrDefaultAsync(m => m.ID == id);
            var currentUser = await GetCurrentUserAsync();

            if (activity.ApplicationUserID == currentUser.Id)
            {
                _context.Activities.Remove(activity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
                return RedirectToAction("AccessDenied", "Account");
        }

ActivityTracker/Controllers/LogEntriesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using ActivityTracker.Data;
using ActivityTracker.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ActivityTracker.Controllers
{
    public class LogEntriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public LogEntriesController(ApplicationDbContext context,
                                    UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: LogEntries/Create
        public IActionResult Create()
        {
            ViewBag.Today = DateTime.Now.ToString("yyyy-MM-dd");
            ViewBag.ActivityId = HttpContext.Request.Query["activityid"];

            return View();
        }

        // POST: LogEntries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ActivityID,Date,TimeSpent,Notes")] LogEntry logEntry)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser student;
                var currentUser = GetCurrentUserAsync().Result;

                if (currentUser.UserType == "S")
                {
                    student = await _context.ApplicationUsers.SingleOrDefaultAsync(s => s.Id == currentUser.Id);
                }
                else
                {
                    return RedirectToAction("AccessDenied", "Account");
                }

                var activity = await _context.Activities.SingleOrDefaultAsync(a => a.ID == logEntry.ActivityID);

                if (activity.ApplicationUserID == Convert.ToString(currentUser.Id))
                {
                    _context.Add(logEntry);
                    await _context.SaveChangesAsync();

                    student.LastActive = logEntry.Date;
                    _context.Update(student);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Details", "Activities", new { id = logEntry.ActivityID });
                }
                else
                    return RedirectToAction("AccessDenied", "Account");
            }
            ViewBag.ActivityId = logEntry.ActivityID;
            return View(logEntry);
        }

        // GET: LogEntries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = GetCurrentUserAsync().Result;
            var logEntry = await _context.LogEntries.SingleOrDefaultAsync(m => m.ID == id);

            if (logEntry == null)
            {
                return NotFound();
            }
            return View(logEntry);
        }

        // POST: LogEntries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ActivityID,Date,TimeSpent,Notes")] LogEntry logEntry)
        {
            if (id != logEntry.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currentUser = GetCurrentUserAsync().Result;
                    var activity = await _context.Activities.SingleOrDefaultAsync(a => a.ID == logEntry.ActivityID);

                    if (activity.ApplicationUserID == Convert.ToString(currentUser.Id))
                    {
                        _context.Update(logEntry);
                        await _context.SaveChangesAsync();
                    }
                    else
                        return RedirectToAction("AccessDenied", "Account");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LogEntryExists(logEntry.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Activities", new { id = logEntry.ActivityID });
            }
            return View(logEntry);
        }

        // GET: LogEntries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = GetCurrentUserAsync().Result;
            var logEntry = await _context.LogEntries
                .SingleOrDefaultAsync(m => m.ID == id);
            var activity = await _context.Activities.SingleOrDefaultAsync(a => a.ID == logEntry.ActivityID);

            if (logEntry == null)
            {
                return NotFound();
            }

            if (activity.ApplicationUserID == Convert.ToString(currentUser.Id))
            {
                return View(logEntry);
            }
            else
                return RedirectToAction("AccessDenied", "Account");
        }

        // POST: LogEntries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var currentUser = GetCurrentUserAsync().Result;
            var logEntry = await _context.LogEntries.SingleOrDefaultAsync(m => m.ID == id);
            var activity = await _context.Activities.SingleOrDefaultAsync(a => a.ID == logEntry.ActivityID);

            if (activity.ApplicationUserID == Convert.ToString(currentUser.Id))
            {
                _context.LogEntries.Remove(logEntry);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Activities", new { id = logEntry.ActivityID });
            }
            else
                return RedirectToAction("AccessDenied", "Account");
        }

        private bool LogEntryExists(int id)
        {
            return _context.LogEntries.Any(e => e.ID == id);
        }
    }
}

ActivityTracker/Views/Activities/Create.cshtml
@model ActivityTracker.Models.Activity

@{
    ViewData["Title"] = "Create";
}

<h2>Create Activity</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <input asp-for="ApplicationUserID" class="form-control" value="@ViewBag.StudentId" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @if (ViewBag.CurrentUserType == "S")
            {
        <div class="form-group">
            <label>Complete</label>
            <div id="switch" class="checkbox">
                <label class="switch">
                    <input type="checkbox" asp-for="Complete" />
                    <span class="slider round"></span>
                </label>
            </div>
        </div>
            <div class="form-group">
                <label asp-for="FunFactor" class="control-label">Fun Factor</label>
                <input type="range" min="1" max="5" list="tickmarks" asp-for="FunFactor" class="form-control">
                <span asp-validation-for="FunFactor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Difficulty" class="control-label"></label>
                <input type="range" min="1" max="5" list="tickmarks" asp-for="Difficulty" class="form-control" />
                <span asp-validation-for="Difficulty" class="text-danger"></span>
            </div>
            <datalist id="tickmarks" hidden>
                <option value="1" />
                <option value="2" />
                <option value="3" />
                <option value="4" />
                <option value="5" />
            </datalist>
            }
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <textarea id="notes" asp-for="Notes" class="form-control"></textarea>
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default"><i class="far fa-save"></i> Save</button> &nbsp;|&nbsp;
                <a asp-action="Index"><i class="fas fa-ban"></i> Cancel</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ActivityTracker/Views/Activities/Delete.cshtml
@model ActivityTracker.Models.Activity

@{
    ViewData["Title"] = "Delete";
}
<h2>Confirm Delete</h2>
<h3>Are you sure you want to delete activity "@Model.Name"?</h3>
@*<br />*@
<div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <button type="submit" class="btn btn-default"><i class="fas fa-trash-alt"></i> Delete</button> &nbsp;|&nbsp;
        <a asp-action="Index"><i class="fas fa-ban"></i> Cancel</a>
    </form>
</div>

ActivityTracker/Views/Activities/Details.cshtml
@model ActivityTracker.Models.Activity

@{
    ViewData["Title"] = "Details " + Model.Name;
}
<div class="row" id="activity-title">
    <div id="activity-name-container" class="form-group col-md-10">
        <input form="activity-form" asp-for="Name" class="form-control input-lg input-header" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="col-md-2 text-right">
        @if (ViewBag.CurrentUser.UserType == "S")
        {
        <form asp-action="Delete" id="delete-activity">
            <input type="hidden" asp-for="ID" />
            <button id="btn-delete" onclick="return confirm('Are you sure you want to delete activity @Model.Name?')"
                    type="submit" value="Delete" class="btn btn-default">
                <i class="fas fa-trash-alt"></i> Delete Activity
            </button>
        </form>
        }
    </div>
</div>
<div class="row" id="activity-details">
    <div id="activity-form-container" class="col-md-4 detail-column">
        <form id="activity-form" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group" hidden>
                <input asp-for="ApplicationUserID" value="@Model.ApplicationUserID" class="form-control" />
            </div>
            <div id="dates">
                <div class="form-group">
                    <div class="date-control">
                        <label>Start Date</label><br />
                        @if (ViewBag.StartDate != null)
                {
                    @ViewBag.StartDate
        }
        else
        {
            <text>-</text>
}
                    </div>
                </div>
                <div class="form-group date-control">
                    <label>Complete</label>
                    <div id="switch" class="checkbox">
                        <label class="switch">
                            <input id="disable1" type="checkbox" asp-for="Complete" />
                            <span class="slider round"></span>
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <div id="last-activity" class="date-control">
                        <label>Last Activity</label><br />
                        @(ViewBag.LastActivity ?? "-")
                    </div>
                </div>
                <div class="form-group date-control">
                    <label>Time Spent</label><br />
                    @(ViewBag.TimeSpent ?? "-")
                </div>
            </div>
            <div class="form-group">
                <label asp-for="FunFactor" class="control-label">Fun Factor</label>
                <input id="disable2" type="range" min="1" max="5" list="tickmarks" asp-for="FunFactor" class="form-control" />
                <span asp-validation-for="FunFactor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Difficulty" class="control-label"></label>
                <input id="disable3" type="range" min="1" max="5" list="tickmarks" asp-for="Difficulty" class="form-control" />
                <span asp-validation-for="Difficulty" class="text-danger"></span>
            </div>
            <datalist id="tickmarks">
                <option value="1" />
                <option value="2" />
                <option value="3" />
                <option value="4" />
                <option value="5" />
            </datalist>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <textarea id="notes" asp-for="Notes" class="form-control"></textarea>
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
            <button type="submit" class="btn btn-default"><i class="far fa-save"></i> Save</button> <text>&nbsp;|&nbsp;</text>
                <a @((ViewBag.CurrentUser.UserType == "S") ? Html.Raw("href='/Activities/Index'") : Html.Raw($"href='/Activities/Index/{Model.ApplicationUserID}'"))>
                    <i class="fas fa-arrow-up"></i> Back to Activities
                </a>
            </div>
        </form>
    </div>
    <div id="log" class="col-md-8">
            <h3>
                Log
                @if (ViewBag.CurrentUser.UserType == "S")
    {
            <text>&nbsp;</text>
            <a asp-controller="LogEntries" asp-action="Create" asp-route-activityid="@Model.ID" class="btn btn-default">
                <i class="fa fa-plus"></i> New Entry
            </a>
}
            </h3>

        <table class="table">
            <thead>
                <tr>
                    <th class="column-sm">
                        Date
                    </th>
                    <th class="text-center column-sm">
                        Hours Spent
                    </th>
                    <th>
                        Notes
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in ViewBag.LogEntries)
            {
                <tr>
                    <td>
                        @item.Date.ToString("dd-MM-yyyy")
                    </td>
                    <td class="text-center">
                        @(item.TimeSpent ?? "-")
                    </td>
                    <td>
                        @Html.Raw(item.Notes)
                    </td>
                <td class="text-right">
                    @if (ViewBag.CurrentUser.UserType == "S")
                    {
                        <a asp-controller="LogEntries" asp-action="Edit" asp-route-id="@item.ID"><i class="fas fa-edit"></i></a>
                    }
                </td>
                </tr>
        }
            </tbody>
        </table>
    </div>
</div>
<br />
<br />

<script>
    if ("@ViewBag.CurrentUser.UserType" === "T") {
        document.getElementById("disable1").disabled = true;
        document.getElementById("disable2").disabled = true;
        document.getElementById("disable3").disabled = true;
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ActivityTracker/Views/Activities/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@if (ViewBag.CurrentUserType == "S")
{
    <h2>My Activities</h2>
}
@if (ViewBag.CurrentUserType == "T")
{
    <h2>
        <i class="fas fa-user"></i> @ViewBag.StudentName
        @if (ViewBag.Groups != null)
        {
            <small>
                @foreach (var group in ViewBag.Groups)
                {
                    @group.Name
                    <text>&nbsp;</text>
                }
            </small>
        }
    </h2>
}

<p>
    <a class="btn btn-default" asp-action="Create" asp-route-studentid="@ViewBag.StudentId"><i class="fas fa-plus"></i> Add Activity</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                Activity
            </th>
            <th class="column-s
                text-center">
                Fun Factor
            </th>
            <th class="column-sm text-center">
                Difficulty
            </th>
            <th>
                Notes
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.Activities)
        {
            <tr class="@(item.Complete ? "complete" : "")">
                <td>
                    <a id="overview-activity-name" asp-action="Details" asp-route-id="@item.ID">@item.Name</a>
                </td>
                <td class="text-center">
                    @for (var i = 0; i < item.FunFactor; i++)
                    {
                        <i class="fas fa-star"></i>
                    }
                </td>
                <td class="text-center">
                    @for (var i = 0; i < item.Difficulty; i++)
                    {
                        <i class="fas fa-star"></i>
                    }
                </td>
                <td>
                    @item.Notes
                </td>
                <td>
                    <div class="text-right">
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                        @if (ViewBag.CurrentUserType == "S")
                        {
                            <text>&nbsp;|&nbsp;</text>
                            <a asp-action="Delete" asp-route-id="@item.ID"><i class="fas fa-trash-alt"></i></a>
                        }
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<br />


@if (ViewBag.CurrentUserType == "T")
{
    <a asp-action="Index" asp-controller="Students"><i class="fas fa-arrow-up"></i> Back to Students</a>
}